In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_probability as tfp
from breakout import Breakout

pygame 2.1.0 (SDL 2.0.16, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [81]:
x = tf.convert_to_tensor([[1,2,3,4,5]])
x = tf.transpose(x)
x.shape

l = [[[320, 320, 490,   4,  -4, 520],
  [330, 316, 486 ,  4,  -4, 520],
  [340, 312, 482,   4 , -4 ,520]], [[320, 320, 490,  -4,  -4, 520],
  [330, 324, 486,  -4 , -4 ,520],
  [340, 328, 482,  -4  ,-4 ,520]]]

ltf = tf.convert_to_tensor(l)
# print(ltf)
shape = ltf.get_shape().as_list()        
dim = np.prod(shape[0:2])
tf.reshape(ltf, [-1, dim]) 
# ltf.shape
r = [[1,2,3,4],[1,2,3,4]]
rtf = tf.convert_to_tensor(r)

print(rtf)
shape = rtf.get_shape().as_list()  
dim = np.prod(shape[-1])
rtf2 = tf.reshape(rtf, (1, dim)) 
rtf2

tf.Tensor(
[[1 2 3 4]
 [1 2 3 4]], shape=(2, 4), dtype=int32)


InvalidArgumentError: Input to reshape is a tensor with 8 values, but the requested shape has 4 [Op:Reshape]

In [72]:
rtf.shape[1]

4

In [46]:
np.array(ltf)

array([[[320, 320, 490,   4,  -4, 520],
        [330, 316, 486,   4,  -4, 520],
        [340, 312, 482,   4,  -4, 520]],

       [[320, 320, 490,  -4,  -4, 520],
        [330, 324, 486,  -4,  -4, 520],
        [340, 328, 482,  -4,  -4, 520]]])

In [5]:
test(10,2)

984

In [6]:
test(8,2)

988

In [7]:
test(3,2)

998

In [2]:
breakout_env = Breakout()

In [3]:
breakout_env.make()

In [5]:
while(True):
    print(breakout_env.step(1))
#     breakout_env.render()

(array([ 30, 101, 498,  -4,  -4, 518]), 0.8999999999999995, False)
(array([ 40, 105, 502,  -4,  -4, 518]), 1.5, False)
(array([ 50, 101, 506,   4,  -3, 518]), 22.9, False)
(array([ 60,  97, 503,   4,  -4, 518]), 24.3, False)
(array([ 70,  93, 499,   4,  -4, 518]), 25.7, False)
(array([ 80,  89, 495,   4,  -4, 518]), 7.1, False)
(array([ 90,  85, 491,   4,  -4, 518]), 7.5, False)
(array([100,  81, 487,   4,  -4, 518]), 6.1, False)
(array([110,  77, 483,   4,  -4, 518]), 4.699999999999999, False)
(array([120,  73, 479,   4,  -4, 518]), 3.3, False)
(array([130,  69, 475,   4,  -4, 518]), 1.8999999999999995, False)
(array([140,  65, 471,   4,  -4, 518]), 0.5, False)
(array([150,  61, 467,   4,  -4, 518]), -0.9000000000000004, False)
(array([160,  57, 463,   4,  -4, 518]), -2.3000000000000007, False)
(array([170,  53, 459,   4,  -4, 518]), -3.700000000000001, False)
(array([180,  49, 455,   4,  -4, 518]), -5.100000000000001, False)
(array([190,  45, 451,   4,  -4, 518]), -6.5, False)
(array

(array([320, 316, 490,   4,  -4, 520]), -2.4000000000000004, True)
(array([330, 312, 486,   4,  -4, 520]), 6.2, False)
(array([340, 308, 482,   4,  -4, 520]), 4.8, False)
(array([350, 304, 478,   4,  -4, 520]), 3.3999999999999995, False)
(array([360, 300, 474,   4,  -4, 520]), 2.0, False)
(array([370, 296, 470,   4,  -4, 520]), 0.5999999999999996, False)
(array([380, 292, 466,   4,  -4, 520]), -0.8000000000000007, False)
(array([390, 288, 462,   4,  -4, 520]), -2.200000000000001, False)
(array([400, 284, 458,   4,  -4, 520]), -3.6000000000000014, False)
(array([410, 280, 454,   4,  -4, 520]), -5.0, False)
(array([420, 276, 450,   4,  -4, 520]), -6.4, False)
(array([430, 272, 446,   4,  -4, 520]), -7.800000000000001, False)
(array([440, 268, 442,   4,  -4, 520]), -9.2, False)
(array([450, 264, 438,   4,  -4, 520]), -10.600000000000001, False)
(array([460, 260, 434,   4,  -4, 520]), -12.0, False)
(array([470, 256, 430,   4,  -4, 520]), -13.400000000000002, False)
(array([480, 252, 426,  

(array([750, 193, 590,  -4,  -4, 518]), -47.7, False)
(array([750, 197, 594,  -4,  -4, 518]), -47.300000000000004, False)
(array([750, 201, 598,  -4,  -4, 518]), -46.900000000000006, False)
(array([320, 316, 490,   4,  -4, 520]), -2.4000000000000004, True)
(array([330, 312, 486,   4,  -4, 520]), 6.2, False)
(array([340, 308, 482,   4,  -4, 520]), 4.8, False)
(array([350, 304, 478,   4,  -4, 520]), 3.3999999999999995, False)
(array([360, 300, 474,   4,  -4, 520]), 2.0, False)
(array([370, 296, 470,   4,  -4, 520]), 0.5999999999999996, False)
(array([380, 292, 466,   4,  -4, 520]), -0.8000000000000007, False)
(array([390, 288, 462,   4,  -4, 520]), -2.200000000000001, False)
(array([400, 284, 458,   4,  -4, 520]), -3.6000000000000014, False)
(array([410, 280, 454,   4,  -4, 520]), -5.0, False)
(array([420, 276, 450,   4,  -4, 520]), -6.4, False)
(array([430, 272, 446,   4,  -4, 520]), -7.800000000000001, False)
(array([440, 268, 442,   4,  -4, 520]), -9.2, False)
(array([450, 264, 438,  

(array([750,  76, 322,   4,  -4, 518]), -59.400000000000006, False)
(array([750,  72, 326,   4,  -4, 518]), -59.8, False)
(array([750,  68, 330,   4,  -4, 518]), -60.2, False)
(array([750,  64, 334,   4,  -4, 518]), -60.60000000000001, False)
(array([750,  60, 338,   4,  -4, 518]), -61.0, False)
(array([750,  56, 342,   4,  -4, 518]), -61.400000000000006, False)
(array([750,  52, 346,   4,  -4, 518]), -61.8, False)
(array([750,  48, 350,   4,  -4, 518]), -62.2, False)
(array([750,  44, 354,   4,  -4, 518]), -62.60000000000001, False)
(array([750,  40, 358,   4,  -4, 518]), -63.0, False)
(array([750,  36, 362,   4,  -4, 518]), -63.400000000000006, False)
(array([750,  32, 366,   4,  -4, 518]), -63.8, False)
(array([750,  28, 370,   4,  -4, 518]), -64.2, False)
(array([750,  24, 374,   4,  -4, 518]), -64.60000000000001, False)
(array([750,  20, 378,   4,  -4, 518]), -65.0, False)
(array([750,  16, 382,   4,  -4, 518]), -65.4, False)
(array([750,  12, 386,   4,  -4, 518]), -65.8, False)
(

(array([750,  69, 466,  -4,  -4, 518]), -60.10000000000001, False)
(array([750,  73, 470,  -4,  -4, 518]), -59.7, False)
(array([750,  77, 474,  -4,  -4, 518]), -59.3, False)
(array([750,  81, 478,  -4,  -4, 518]), -58.900000000000006, False)
(array([750,  85, 482,  -4,  -4, 518]), -58.5, False)
(array([750,  89, 486,  -4,  -4, 518]), -58.10000000000001, False)
(array([750,  93, 490,  -4,  -4, 518]), -57.7, False)
(array([750,  97, 494,  -4,  -4, 518]), -57.3, False)
(array([750, 101, 498,  -4,  -4, 518]), -56.900000000000006, False)
(array([750, 105, 502,  -4,  -4, 518]), -56.5, False)
(array([750, 109, 506,  -4,  -4, 518]), -56.10000000000001, False)
(array([750, 113, 510,  -4,  -4, 518]), -55.7, False)
(array([750, 117, 514,  -4,  -4, 518]), -55.300000000000004, False)
(array([750, 121, 518,  -4,  -4, 518]), -54.900000000000006, False)
(array([750, 125, 522,  -4,  -4, 518]), -54.5, False)
(array([750, 129, 526,  -4,  -4, 518]), -54.1, False)
(array([750, 133, 530,  -4,  -4, 518]), -

(array([750, 116, 290,   4,  -4, 520]), -55.400000000000006, False)
(array([750, 112, 286,   4,  -4, 518]), -55.800000000000004, False)
(array([750, 108, 290,   4,  -4, 518]), -56.2, False)
(array([750, 104, 294,   4,  -4, 518]), -56.60000000000001, False)
(array([750, 100, 298,   4,  -4, 518]), -57.0, False)
(array([750,  96, 302,   4,  -4, 518]), -57.400000000000006, False)
(array([750,  92, 306,   4,  -4, 518]), -57.8, False)
(array([750,  88, 310,   4,  -4, 518]), -58.2, False)
(array([750,  84, 314,   4,  -4, 518]), -58.60000000000001, False)
(array([750,  80, 318,   4,  -4, 518]), -59.0, False)
(array([750,  76, 322,   4,  -4, 518]), -59.400000000000006, False)
(array([750,  72, 326,   4,  -4, 518]), -59.8, False)
(array([750,  68, 330,   4,  -4, 518]), -60.2, False)
(array([750,  64, 334,   4,  -4, 518]), -60.60000000000001, False)
(array([750,  60, 338,   4,  -4, 518]), -61.0, False)
(array([750,  56, 342,   4,  -4, 518]), -61.400000000000006, False)
(array([750,  52, 346,   4,

(array([750, 108, 290,   4,  -4, 518]), -56.2, False)
(array([750, 104, 294,   4,  -4, 518]), -56.60000000000001, False)
(array([750, 100, 298,   4,  -4, 518]), -57.0, False)
(array([750,  96, 302,   4,  -4, 518]), -57.400000000000006, False)
(array([750,  92, 306,   4,  -4, 518]), -57.8, False)
(array([750,  88, 310,   4,  -4, 518]), -58.2, False)
(array([750,  84, 314,   4,  -4, 518]), -58.60000000000001, False)
(array([750,  80, 318,   4,  -4, 518]), -59.0, False)
(array([750,  76, 322,   4,  -4, 518]), -59.400000000000006, False)
(array([750,  72, 326,   4,  -4, 518]), -59.8, False)
(array([750,  68, 330,   4,  -4, 518]), -60.2, False)
(array([750,  64, 334,   4,  -4, 518]), -60.60000000000001, False)
(array([750,  60, 338,   4,  -4, 518]), -61.0, False)
(array([750,  56, 342,   4,  -4, 518]), -61.400000000000006, False)
(array([750,  52, 346,   4,  -4, 518]), -61.8, False)
(array([750,  48, 350,   4,  -4, 518]), -62.2, False)
(array([750,  44, 354,   4,  -4, 518]), -62.60000000000

(array([410, 280, 454,   4,  -4, 520]), -5.0, False)
(array([420, 276, 450,   4,  -4, 520]), -6.4, False)
(array([430, 272, 446,   4,  -4, 520]), -7.800000000000001, False)
(array([440, 268, 442,   4,  -4, 520]), -9.2, False)
(array([450, 264, 438,   4,  -4, 520]), -10.600000000000001, False)
(array([460, 260, 434,   4,  -4, 520]), -12.0, False)
(array([470, 256, 430,   4,  -4, 520]), -13.400000000000002, False)
(array([480, 252, 426,   4,  -4, 520]), -14.8, False)
(array([490, 248, 422,   4,  -4, 520]), -16.200000000000003, False)
(array([500, 244, 418,   4,  -4, 520]), -17.6, False)
(array([510, 240, 414,   4,  -4, 520]), -19.0, False)
(array([520, 236, 410,   4,  -4, 520]), -20.400000000000002, False)
(array([530, 232, 406,   4,  -4, 520]), -21.8, False)
(array([540, 228, 402,   4,  -4, 520]), -23.200000000000003, False)
(array([550, 224, 398,   4,  -4, 520]), -24.6, False)
(array([560, 220, 394,   4,  -4, 520]), -26.0, False)
(array([570, 216, 390,   4,  -4, 520]), -27.4, False)
(a

(array([750,  40, 358,   4,  -4, 518]), -63.0, False)
(array([750,  36, 362,   4,  -4, 518]), -63.400000000000006, False)
(array([750,  32, 366,   4,  -4, 518]), -63.8, False)
(array([750,  28, 370,   4,  -4, 518]), -64.2, False)
(array([750,  24, 374,   4,  -4, 518]), -64.60000000000001, False)
(array([750,  20, 378,   4,  -4, 518]), -65.0, False)
(array([750,  16, 382,   4,  -4, 518]), -65.4, False)
(array([750,  12, 386,   4,  -4, 518]), -65.8, False)
(array([750,   8, 390,   4,  -4, 518]), -66.2, False)
(array([750,   4, 394,   4,  -4, 518]), -66.60000000000001, False)
(array([750,   1, 398,  -4,  -4, 518]), -66.9, False)
(array([750,   5, 402,  -4,  -4, 518]), -66.5, False)
(array([750,   9, 406,  -4,  -4, 518]), -66.10000000000001, False)
(array([750,  13, 410,  -4,  -4, 518]), -65.7, False)
(array([750,  17, 414,  -4,  -4, 518]), -65.3, False)
(array([750,  21, 418,  -4,  -4, 518]), -64.9, False)
(array([750,  25, 422,  -4,  -4, 518]), -64.5, False)
(array([750,  29, 426,  -4,  

(array([580, 212, 386,   4,  -4, 520]), -28.800000000000004, False)
(array([590, 208, 382,   4,  -4, 520]), -30.200000000000003, False)
(array([600, 204, 378,   4,  -4, 520]), -31.6, False)
(array([610, 200, 374,   4,  -4, 520]), -33.0, False)
(array([620, 196, 370,   4,  -4, 520]), -34.400000000000006, False)
(array([630, 192, 366,   4,  -4, 520]), -35.800000000000004, False)
(array([640, 188, 362,   4,  -4, 520]), -37.2, False)
(array([650, 184, 358,   4,  -4, 520]), -38.6, False)
(array([660, 180, 354,   4,  -4, 520]), -40.0, False)
(array([670, 176, 350,   4,  -4, 520]), -41.400000000000006, False)
(array([680, 172, 346,   4,  -4, 520]), -42.800000000000004, False)
(array([690, 168, 342,   4,  -4, 520]), -44.2, False)
(array([700, 164, 338,   4,  -4, 520]), -45.6, False)
(array([710, 160, 334,   4,  -4, 520]), -47.0, False)
(array([720, 156, 330,   4,  -4, 520]), -48.400000000000006, False)
(array([730, 152, 326,   4,  -4, 520]), -49.800000000000004, False)
(array([740, 148, 322,  

(array([750,  65, 462,  -4,  -4, 518]), -60.5, False)
(array([750,  69, 466,  -4,  -4, 518]), -60.10000000000001, False)
(array([750,  73, 470,  -4,  -4, 518]), -59.7, False)
(array([750,  77, 474,  -4,  -4, 518]), -59.3, False)
(array([750,  81, 478,  -4,  -4, 518]), -58.900000000000006, False)
(array([750,  85, 482,  -4,  -4, 518]), -58.5, False)
(array([750,  89, 486,  -4,  -4, 518]), -58.10000000000001, False)
(array([750,  93, 490,  -4,  -4, 518]), -57.7, False)
(array([750,  97, 494,  -4,  -4, 518]), -57.3, False)
(array([750, 101, 498,  -4,  -4, 518]), -56.900000000000006, False)
(array([750, 105, 502,  -4,  -4, 518]), -56.5, False)
(array([750, 109, 506,  -4,  -4, 518]), -56.10000000000001, False)
(array([750, 113, 510,  -4,  -4, 518]), -55.7, False)
(array([750, 117, 514,  -4,  -4, 518]), -55.300000000000004, False)
(array([750, 121, 518,  -4,  -4, 518]), -54.900000000000006, False)
(array([750, 125, 522,  -4,  -4, 518]), -54.5, False)
(array([750, 129, 526,  -4,  -4, 518]), -

(array([750,  24, 374,   4,  -4, 518]), -64.60000000000001, False)
(array([750,  20, 378,   4,  -4, 518]), -65.0, False)
(array([750,  16, 382,   4,  -4, 518]), -65.4, False)
(array([750,  12, 386,   4,  -4, 518]), -65.8, False)
(array([750,   8, 390,   4,  -4, 518]), -66.2, False)
(array([750,   4, 394,   4,  -4, 518]), -66.60000000000001, False)
(array([750,   1, 398,  -4,  -4, 518]), -66.9, False)
(array([750,   5, 402,  -4,  -4, 518]), -66.5, False)
(array([750,   9, 406,  -4,  -4, 518]), -66.10000000000001, False)
(array([750,  13, 410,  -4,  -4, 518]), -65.7, False)
(array([750,  17, 414,  -4,  -4, 518]), -65.3, False)
(array([750,  21, 418,  -4,  -4, 518]), -64.9, False)
(array([750,  25, 422,  -4,  -4, 518]), -64.5, False)
(array([750,  29, 426,  -4,  -4, 518]), -64.10000000000001, False)
(array([750,  33, 430,  -4,  -4, 518]), -63.7, False)
(array([750,  37, 434,  -4,  -4, 518]), -63.3, False)
(array([750,  41, 438,  -4,  -4, 518]), -62.900000000000006, False)
(array([750,  45

(array([750, 121, 518,  -4,  -4, 518]), -54.900000000000006, False)
(array([750, 125, 522,  -4,  -4, 518]), -54.5, False)
(array([750, 129, 526,  -4,  -4, 518]), -54.1, False)
(array([750, 133, 530,  -4,  -4, 518]), -53.7, False)
(array([750, 137, 534,  -4,  -4, 518]), -53.300000000000004, False)
(array([750, 141, 538,  -4,  -4, 518]), -52.900000000000006, False)
(array([750, 145, 542,  -4,  -4, 518]), -52.5, False)
(array([750, 149, 546,  -4,  -4, 518]), -52.1, False)
(array([750, 153, 550,  -4,  -4, 518]), -51.7, False)
(array([750, 157, 554,  -4,  -4, 518]), -51.300000000000004, False)
(array([750, 161, 558,  -4,  -4, 518]), -50.900000000000006, False)
(array([750, 165, 562,  -4,  -4, 518]), -50.5, False)
(array([750, 169, 566,  -4,  -4, 518]), -50.1, False)
(array([750, 173, 570,  -4,  -4, 518]), -49.7, False)
(array([750, 177, 574,  -4,  -4, 518]), -49.300000000000004, False)
(array([750, 181, 578,  -4,  -4, 518]), -48.900000000000006, False)
(array([750, 185, 582,  -4,  -4, 518])

(array([750,  40, 358,   4,  -4, 518]), -63.0, False)
(array([750,  36, 362,   4,  -4, 518]), -63.400000000000006, False)
(array([750,  32, 366,   4,  -4, 518]), -63.8, False)
(array([750,  28, 370,   4,  -4, 518]), -64.2, False)
(array([750,  24, 374,   4,  -4, 518]), -64.60000000000001, False)
(array([750,  20, 378,   4,  -4, 518]), -65.0, False)
(array([750,  16, 382,   4,  -4, 518]), -65.4, False)
(array([750,  12, 386,   4,  -4, 518]), -65.8, False)
(array([750,   8, 390,   4,  -4, 518]), -66.2, False)
(array([750,   4, 394,   4,  -4, 518]), -66.60000000000001, False)
(array([750,   1, 398,  -4,  -4, 518]), -66.9, False)
(array([750,   5, 402,  -4,  -4, 518]), -66.5, False)
(array([750,   9, 406,  -4,  -4, 518]), -66.10000000000001, False)
(array([750,  13, 410,  -4,  -4, 518]), -65.7, False)
(array([750,  17, 414,  -4,  -4, 518]), -65.3, False)
(array([750,  21, 418,  -4,  -4, 518]), -64.9, False)
(array([750,  25, 422,  -4,  -4, 518]), -64.5, False)
(array([750,  29, 426,  -4,  

(array([750, 117, 514,  -4,  -4, 518]), -55.300000000000004, False)
(array([750, 121, 518,  -4,  -4, 518]), -54.900000000000006, False)
(array([750, 125, 522,  -4,  -4, 518]), -54.5, False)
(array([750, 129, 526,  -4,  -4, 518]), -54.1, False)
(array([750, 133, 530,  -4,  -4, 518]), -53.7, False)
(array([750, 137, 534,  -4,  -4, 518]), -53.300000000000004, False)
(array([750, 141, 538,  -4,  -4, 518]), -52.900000000000006, False)
(array([750, 145, 542,  -4,  -4, 518]), -52.5, False)
(array([750, 149, 546,  -4,  -4, 518]), -52.1, False)
(array([750, 153, 550,  -4,  -4, 518]), -51.7, False)
(array([750, 157, 554,  -4,  -4, 518]), -51.300000000000004, False)
(array([750, 161, 558,  -4,  -4, 518]), -50.900000000000006, False)
(array([750, 165, 562,  -4,  -4, 518]), -50.5, False)
(array([750, 169, 566,  -4,  -4, 518]), -50.1, False)
(array([750, 173, 570,  -4,  -4, 518]), -49.7, False)
(array([750, 177, 574,  -4,  -4, 518]), -49.300000000000004, False)
(array([750, 181, 578,  -4,  -4, 518])

(array([750, 125, 522,  -4,  -4, 518]), -54.5, False)
(array([750, 129, 526,  -4,  -4, 518]), -54.1, False)
(array([750, 133, 530,  -4,  -4, 518]), -53.7, False)
(array([750, 137, 534,  -4,  -4, 518]), -53.300000000000004, False)
(array([750, 141, 538,  -4,  -4, 518]), -52.900000000000006, False)
(array([750, 145, 542,  -4,  -4, 518]), -52.5, False)
(array([750, 149, 546,  -4,  -4, 518]), -52.1, False)
(array([750, 153, 550,  -4,  -4, 518]), -51.7, False)
(array([750, 157, 554,  -4,  -4, 518]), -51.300000000000004, False)
(array([750, 161, 558,  -4,  -4, 518]), -50.900000000000006, False)
(array([750, 165, 562,  -4,  -4, 518]), -50.5, False)
(array([750, 169, 566,  -4,  -4, 518]), -50.1, False)
(array([750, 173, 570,  -4,  -4, 518]), -49.7, False)
(array([750, 177, 574,  -4,  -4, 518]), -49.300000000000004, False)
(array([750, 181, 578,  -4,  -4, 518]), -48.900000000000006, False)
(array([750, 185, 582,  -4,  -4, 518]), -48.5, False)
(array([750, 189, 586,  -4,  -4, 518]), -48.1, False

(array([750, 128, 302,   4,  -4, 520]), -54.2, False)
(array([750, 124, 298,   4,  -4, 520]), -54.6, False)
(array([750, 120, 294,   4,  -4, 520]), -55.0, False)
(array([750, 116, 290,   4,  -4, 520]), -55.400000000000006, False)
(array([750, 112, 286,   4,  -4, 518]), -55.800000000000004, False)
(array([750, 108, 290,   4,  -4, 518]), -56.2, False)
(array([750, 104, 294,   4,  -4, 518]), -56.60000000000001, False)
(array([750, 100, 298,   4,  -4, 518]), -57.0, False)
(array([750,  96, 302,   4,  -4, 518]), -57.400000000000006, False)
(array([750,  92, 306,   4,  -4, 518]), -57.8, False)
(array([750,  88, 310,   4,  -4, 518]), -58.2, False)
(array([750,  84, 314,   4,  -4, 518]), -58.60000000000001, False)
(array([750,  80, 318,   4,  -4, 518]), -59.0, False)
(array([750,  76, 322,   4,  -4, 518]), -59.400000000000006, False)
(array([750,  72, 326,   4,  -4, 518]), -59.8, False)
(array([750,  68, 330,   4,  -4, 518]), -60.2, False)
(array([750,  64, 334,   4,  -4, 518]), -60.6000000000

(array([750,  16, 382,   4,  -4, 518]), -65.4, False)
(array([750,  12, 386,   4,  -4, 518]), -65.8, False)
(array([750,   8, 390,   4,  -4, 518]), -66.2, False)
(array([750,   4, 394,   4,  -4, 518]), -66.60000000000001, False)
(array([750,   1, 398,  -4,  -4, 518]), -66.9, False)
(array([750,   5, 402,  -4,  -4, 518]), -66.5, False)
(array([750,   9, 406,  -4,  -4, 518]), -66.10000000000001, False)
(array([750,  13, 410,  -4,  -4, 518]), -65.7, False)
(array([750,  17, 414,  -4,  -4, 518]), -65.3, False)
(array([750,  21, 418,  -4,  -4, 518]), -64.9, False)
(array([750,  25, 422,  -4,  -4, 518]), -64.5, False)
(array([750,  29, 426,  -4,  -4, 518]), -64.10000000000001, False)
(array([750,  33, 430,  -4,  -4, 518]), -63.7, False)
(array([750,  37, 434,  -4,  -4, 518]), -63.3, False)
(array([750,  41, 438,  -4,  -4, 518]), -62.900000000000006, False)
(array([750,  45, 442,  -4,  -4, 518]), -62.5, False)
(array([750,  49, 446,  -4,  -4, 518]), -62.10000000000001, False)
(array([750,  53

(array([750, 165, 562,  -4,  -4, 518]), -50.5, False)
(array([750, 169, 566,  -4,  -4, 518]), -50.1, False)
(array([750, 173, 570,  -4,  -4, 518]), -49.7, False)
(array([750, 177, 574,  -4,  -4, 518]), -49.300000000000004, False)
(array([750, 181, 578,  -4,  -4, 518]), -48.900000000000006, False)
(array([750, 185, 582,  -4,  -4, 518]), -48.5, False)
(array([750, 189, 586,  -4,  -4, 518]), -48.1, False)
(array([750, 193, 590,  -4,  -4, 518]), -47.7, False)
(array([750, 197, 594,  -4,  -4, 518]), -47.300000000000004, False)
(array([750, 201, 598,  -4,  -4, 518]), -46.900000000000006, False)
(array([320, 316, 490,   4,  -4, 520]), -2.4000000000000004, True)
(array([330, 312, 486,   4,  -4, 520]), 6.2, False)
(array([340, 308, 482,   4,  -4, 520]), 4.8, False)
(array([350, 304, 478,   4,  -4, 520]), 3.3999999999999995, False)
(array([360, 300, 474,   4,  -4, 520]), 2.0, False)
(array([370, 296, 470,   4,  -4, 520]), 0.5999999999999996, False)
(array([380, 292, 466,   4,  -4, 520]), -0.8000

(array([750, 177, 574,  -4,  -4, 518]), -49.300000000000004, False)
(array([750, 181, 578,  -4,  -4, 518]), -48.900000000000006, False)
(array([750, 185, 582,  -4,  -4, 518]), -48.5, False)
(array([750, 189, 586,  -4,  -4, 518]), -48.1, False)
(array([750, 193, 590,  -4,  -4, 518]), -47.7, False)
(array([750, 197, 594,  -4,  -4, 518]), -47.300000000000004, False)
(array([750, 201, 598,  -4,  -4, 518]), -46.900000000000006, False)
(array([320, 316, 490,   4,  -4, 520]), -2.4000000000000004, True)
(array([330, 312, 486,   4,  -4, 520]), 6.2, False)
(array([340, 308, 482,   4,  -4, 520]), 4.8, False)
(array([350, 304, 478,   4,  -4, 520]), 3.3999999999999995, False)
(array([360, 300, 474,   4,  -4, 520]), 2.0, False)
(array([370, 296, 470,   4,  -4, 520]), 0.5999999999999996, False)
(array([380, 292, 466,   4,  -4, 520]), -0.8000000000000007, False)
(array([390, 288, 462,   4,  -4, 520]), -2.200000000000001, False)
(array([400, 284, 458,   4,  -4, 520]), -3.6000000000000014, False)
(array

(array([750,  92, 306,   4,  -4, 518]), -57.8, False)
(array([750,  88, 310,   4,  -4, 518]), -58.2, False)
(array([750,  84, 314,   4,  -4, 518]), -58.60000000000001, False)
(array([750,  80, 318,   4,  -4, 518]), -59.0, False)
(array([750,  76, 322,   4,  -4, 518]), -59.400000000000006, False)
(array([750,  72, 326,   4,  -4, 518]), -59.8, False)
(array([750,  68, 330,   4,  -4, 518]), -60.2, False)
(array([750,  64, 334,   4,  -4, 518]), -60.60000000000001, False)
(array([750,  60, 338,   4,  -4, 518]), -61.0, False)
(array([750,  56, 342,   4,  -4, 518]), -61.400000000000006, False)
(array([750,  52, 346,   4,  -4, 518]), -61.8, False)
(array([750,  48, 350,   4,  -4, 518]), -62.2, False)
(array([750,  44, 354,   4,  -4, 518]), -62.60000000000001, False)
(array([750,  40, 358,   4,  -4, 518]), -63.0, False)
(array([750,  36, 362,   4,  -4, 518]), -63.400000000000006, False)
(array([750,  32, 366,   4,  -4, 518]), -63.8, False)
(array([750,  28, 370,   4,  -4, 518]), -64.2, False)
(

(array([510, 240, 414,   4,  -4, 520]), -19.0, False)
(array([520, 236, 410,   4,  -4, 520]), -20.400000000000002, False)
(array([530, 232, 406,   4,  -4, 520]), -21.8, False)
(array([540, 228, 402,   4,  -4, 520]), -23.200000000000003, False)
(array([550, 224, 398,   4,  -4, 520]), -24.6, False)
(array([560, 220, 394,   4,  -4, 520]), -26.0, False)
(array([570, 216, 390,   4,  -4, 520]), -27.4, False)
(array([580, 212, 386,   4,  -4, 520]), -28.800000000000004, False)
(array([590, 208, 382,   4,  -4, 520]), -30.200000000000003, False)
(array([600, 204, 378,   4,  -4, 520]), -31.6, False)
(array([610, 200, 374,   4,  -4, 520]), -33.0, False)
(array([620, 196, 370,   4,  -4, 520]), -34.400000000000006, False)
(array([630, 192, 366,   4,  -4, 520]), -35.800000000000004, False)
(array([640, 188, 362,   4,  -4, 520]), -37.2, False)
(array([650, 184, 358,   4,  -4, 520]), -38.6, False)
(array([660, 180, 354,   4,  -4, 520]), -40.0, False)
(array([670, 176, 350,   4,  -4, 520]), -41.40000000

(array([750,  44, 354,   4,  -4, 518]), -62.60000000000001, False)
(array([750,  40, 358,   4,  -4, 518]), -63.0, False)
(array([750,  36, 362,   4,  -4, 518]), -63.400000000000006, False)
(array([750,  32, 366,   4,  -4, 518]), -63.8, False)
(array([750,  28, 370,   4,  -4, 518]), -64.2, False)
(array([750,  24, 374,   4,  -4, 518]), -64.60000000000001, False)
(array([750,  20, 378,   4,  -4, 518]), -65.0, False)
(array([750,  16, 382,   4,  -4, 518]), -65.4, False)
(array([750,  12, 386,   4,  -4, 518]), -65.8, False)
(array([750,   8, 390,   4,  -4, 518]), -66.2, False)
(array([750,   4, 394,   4,  -4, 518]), -66.60000000000001, False)
(array([750,   1, 398,  -4,  -4, 518]), -66.9, False)
(array([750,   5, 402,  -4,  -4, 518]), -66.5, False)
(array([750,   9, 406,  -4,  -4, 518]), -66.10000000000001, False)
(array([750,  13, 410,  -4,  -4, 518]), -65.7, False)
(array([750,  17, 414,  -4,  -4, 518]), -65.3, False)
(array([750,  21, 418,  -4,  -4, 518]), -64.9, False)
(array([750,  25

KeyboardInterrupt: 

In [3]:
print("action space: ", breakout_env.action_space)
print("observation space: ", breakout_env.observation_space)

action space:  3
observation space:  6


In [3]:
# running this will run the playable game
breakout_env.main()

brick hit
missed paddle
brick hit
missed paddle


KeyboardInterrupt: 

In [3]:
# run this initially to make the brick layout
breakout_env.make()

In [4]:
breakout_env.step(1)

(array([330, 296, 486,   4,  -4, 520]), 4.6, False)

In [5]:
breakout_env.step(0)

(array([320, 292, 482,   4,  -4, 520]), 5.199999999999999, False)

In [6]:
breakout_env.step(0)

(array([310, 288, 478,   4,  -4, 520]), 5.8, False)

In [7]:
breakout_env.step(0)

(array([300, 284, 474,   4,  -4, 520]), 6.4, False)

In [8]:
breakout_env.step(0)

(array([290, 280, 470,   4,  -4, 520]), 7.0, False)

In [9]:
breakout_env.step(0)

(array([280, 276, 466,   4,  -4, 520]), 7.6, False)

In [10]:
breakout_env.step(0)

(array([270, 272, 462,   4,  -4, 520]), 7.8, False)

In [11]:
class Agent():
    def __init__(self, observation_dim, params = None, action_bounds = None):
        pass

    def __call__(self, obs):
        return self.act(obs)

In [12]:
# REINFORCE

In [13]:
N_EPISODES = 50 # Change this if you find this is not sufficient

In [45]:
l = np.random.rand(3,2)
l.shape

(3, 2)

In [15]:
def roundToNearest(numbers, toRound):
    distance = np.zeros(len(numbers))
    for i in range(len(numbers)):
        distance[i] = abs(numbers[i] - toRound)
    
    return np.argmin(distance)
        

In [16]:
roundToNearest([1,20, 50, 100], 11)

1

In [11]:
class GaussianPolicy(Agent):
    
    def __init__(self, observation_dim, params = None, action_bounds = None,
                 gamma=0.9, alpha = 0.1, sigma = 0.1):   
        self.states = observation_dim # dimension of observations

        # Action bounds are limits of shape (2,),
        # representing the lower/upper limits on the action
        self.action_bounds = action_bounds 
        
        self.gamma = gamma
        
        # Initial parameters of the policy
        self.params = params
        self.sigma = sigma
        
        self.alpha = alpha
        
    def act(self, obs):
        '''
        obs: Array of size (n, observation_dims) representing a batch of observations,
        which are each a vector of (observation_dims)

        Returns:
        actions: Array of size (n, 1) representing actions determined by params, self.sigma
        '''
#         print(obs)
        theta = self.params
        states = obs
        
        a = np.random.normal(loc=states.dot(theta))
        
        ret = (1/np.sqrt(2*np.pi*self.sigma))*np.exp((-1/(2*self.sigma)) * (a - states.dot(theta)))
        possible_actions = [0,1,2]
        clipped_action = roundToNearest(possible_actions, ret)
        
        return clipped_action # TODO: Write code here

    def update(self, obs, actions, rewards):
        '''
        obs: Array of size (n+1, observation_dims) representing a batch of observations,
        which are each a vector of (observation_dims)
        rewards: Array of size (n,) representing a batch of rewards
        actions: Array of size (n,) representing a batch of actions

        Returns:
        Nothing, modifies parameters according to the REINFORCE algorithm
        '''
        
        cost = 0
        for i in range(len(obs)):
            if i != len(obs) - 1:
                states = obs[i]
                action = actions[i]
                reward = rewards[i]
                
                gaussian_grad = ((action - states.dot(self.params))*states)/self.sigma
                
                score = gaussian_grad*reward
                
                cost+=score
        
        self.params = self.params + self.alpha*cost
        
        return # TODO: Write code here
    
    def collect_data(self, task):
        # Do not modify
        obs = task.reset()

        rewards = np.zeros((100,))
        states = np.zeros((101, self.states))
        actions = np.zeros((100, 1))
        
        for step in range(100):
            states[step, :] = obs
            act = self.__call__(obs)
#             print(act)
            obs, rew, done = task.step(act)
            rewards[step] = rew
            actions[step] = act
#             print(rew)
            
        states[-1, :] = obs
#         print(states, "--")
#         print(rewards)
        
        return states, actions, rewards

# Do not modify
init_mu = np.random.random((breakout_env.observation_space,))

agent = GaussianPolicy(breakout_env.observation_space, init_mu, [breakout_env.min_action, breakout_env.max_action])

rewards = []

for i in range(N_EPISODES):
    data = agent.collect_data(breakout_env)

    rewards.append(np.mean(data[2]))
    agent.update(*data)

plt.plot(np.arange(N_EPISODES), rewards)
# Final Benchmarking
rewards = np.zeros((100, 100))

for i in range(100):
    rewards[i] = agent.collect_data(breakout_env)[2]
        
print("Average return: {}".format(rewards.sum(1).mean()))
print("Standard deviation: {}".format(rewards.sum(1).std()))

NameError: name 'Agent' is not defined

In [14]:
# using https://towardsdatascience.com/reinforce-policy-gradient-with-tensorflow2-x-be1dea695f24 instead

In [12]:
class model(tf.keras.Model):
    def __init__(self, observation_space, action_space):
        super().__init__()
        self.d1 = tf.keras.layers.Dense(30,input_dim=observation_space,activation='relu')
        self.d2 = tf.keras.layers.Dense(30,activation='relu')
        self.out = tf.keras.layers.Dense(action_space,activation='softmax')

    def call(self, input_data):
        x = tf.convert_to_tensor(input_data)
        x = self.d1(x)
        x = self.d2(x)
        x = self.out(x)
        return x

    def action_value(self, state):
        p = self.predict(state)
        return p

In [9]:
class AgentReinforce():
    def __init__(self, observation_space, action_space):
        self.model = model(observation_space, action_space)
        self.opt = tf.keras.optimizers.Adam(learning_rate=0.001)
        self.gamma = 1

    def act(self,state):
        prob = self.model(np.array([state]))
        dist = tfp.distributions.Categorical(probs=prob, dtype=tf.float32)
        action = dist.sample()
#         print(prob)
#         print(dist)
#         print(action)
#         print("---")
        if int(action.numpy()[0]) > 2:
            return 2
        elif int(action.numpy()[0]) < 0:
            return 0
        
        return int(action.numpy()[0])

    def a_loss(self,prob, action, reward): 
#         print(prob)
#         print(action)
#         action_list = [0,1,2]
#         clipped_action = roundToNearest(action_list, action)
#         print("action and clipped action: ", action, clipped_action)
#         print(reward)
#         print("-------")
        dist = tfp.distributions.Categorical(probs=prob, dtype=tf.float32)
        log_prob = dist.log_prob(action)
        loss = -log_prob*reward
        return loss 

    def train(self, states, rewards, actions):
        sum_reward = 0
        discnt_rewards = []
        rewards.reverse()
        for r in rewards:
            sum_reward = r + self.gamma*sum_reward
            discnt_rewards.append(sum_reward)
        discnt_rewards.reverse()  

        for state, reward, action in zip(states, discnt_rewards, actions):
#             print("s" , action)
            with tf.GradientTape() as tape:
                p = self.model(np.array([state]), training=True)
                loss = self.a_loss(p, action, reward)
            grads = tape.gradient(loss, self.model.trainable_variables)
            self.opt.apply_gradients(zip(grads, self.model.trainable_variables))

In [24]:
100%200 !=0

True

In [16]:
np.random.random()

0.16474179246866127

In [51]:
(0.9/1000)*100
e = 0.9
act = []
rand = [] 
for j in range(1,1000):
    for k in range(10):
        p = np.random.random()
        if p < 1 - e:
            print("act")
        else:
            print("random")
    e = (0.9/j)*100
    print(j, e)


random
random
random
random
random
random
random
random
random
random
1 90.0
random
random
random
random
random
random
random
random
random
random
2 45.0
random
random
random
random
random
random
random
random
random
random
3 30.0
random
random
random
random
random
random
random
random
random
random
4 22.5
random
random
random
random
random
random
random
random
random
random
5 18.0
random
random
random
random
random
random
random
random
random
random
6 15.0
random
random
random
random
random
random
random
random
random
random
7 12.85714285714286
random
random
random
random
random
random
random
random
random
random
8 11.25
random
random
random
random
random
random
random
random
random
random
9 10.0
random
random
random
random
random
random
random
random
random
random
10 9.0
random
random
random
random
random
random
random
random
random
random
11 8.181818181818182
random
random
random
random
random
random
random
random
random
random
12 7.5
random
random
random
random
random
random
random

116 0.7758620689655172
random
act
random
random
random
random
act
random
random
random
117 0.7692307692307693
random
random
act
random
random
random
random
random
random
act
118 0.7627118644067797
act
random
random
random
act
random
random
random
act
act
119 0.7563025210084033
act
random
random
act
random
random
random
random
random
random
120 0.7500000000000001
random
random
random
random
act
act
random
random
random
act
121 0.743801652892562
act
act
act
act
random
act
random
act
act
random
122 0.7377049180327869
random
random
random
random
random
act
random
random
random
random
123 0.7317073170731708
random
act
act
random
random
random
random
act
random
random
124 0.7258064516129032
act
random
act
act
random
act
random
act
random
random
125 0.72
random
random
random
act
random
act
act
random
random
random
126 0.7142857142857143
random
random
act
random
act
random
random
random
act
random
127 0.7086614173228346
random
random
random
random
random
random
random
act
random
random
128 0.7

233 0.38626609442060084
act
act
act
act
random
act
act
act
random
random
234 0.38461538461538464
act
random
random
act
act
random
act
act
random
random
235 0.3829787234042553
random
act
random
act
act
random
act
random
act
act
236 0.38135593220338987
act
act
act
act
random
act
act
random
random
act
237 0.379746835443038
act
act
act
act
act
random
random
act
act
random
238 0.37815126050420167
random
act
random
act
act
act
act
act
act
act
239 0.37656903765690375
random
random
random
act
act
act
random
act
act
act
240 0.37500000000000006
random
random
act
random
act
act
act
act
act
act
241 0.37344398340248963
act
random
random
act
random
act
random
act
act
random
242 0.371900826446281
random
act
act
act
random
act
act
act
random
random
243 0.3703703703703704
act
act
act
act
random
random
act
random
random
act
244 0.36885245901639346
random
act
act
act
act
act
act
random
act
act
245 0.3673469387755102
random
act
random
act
random
act
random
random
act
act
246 0.3658536585365854
act
act
ran

random
random
act
act
act
random
random
act
366 0.24590163934426232
act
act
act
act
act
random
random
act
act
act
367 0.2452316076294278
random
act
act
act
act
act
act
act
random
act
368 0.24456521739130438
act
act
act
act
act
act
act
random
act
act
369 0.24390243902439024
act
act
act
act
act
act
act
act
act
act
370 0.24324324324324323
act
act
act
act
act
act
act
act
act
act
371 0.24258760107816713
act
act
act
act
act
act
act
random
act
act
372 0.24193548387096775
random
act
act
random
random
act
act
act
random
act
373 0.2412868632707775
act
act
act
act
act
random
act
act
random
act
374 0.24064171122994654
random
act
random
act
act
random
random
act
act
act
375 0.24000000000000002
act
act
act
act
random
act
act
act
act
random
376 0.23936170212765956
random
act
act
random
act
random
act
act
act
act
377 0.2387267904509284
act
act
random
act
random
act
act
act
act
act
378 0.2380952380952381
act
act
act
act
act
act
act
act
act
random
379 0.23746701846965698
act
random
random
act
act
act
ra

493 0.18255578093306288
act
act
random
act
act
act
act
act
act
act
494 0.18218623481781376
act
act
act
act
act
act
random
act
random
act
495 0.18181818181818182
act
act
act
act
act
act
act
random
act
act
496 0.1814516129032258
act
act
random
act
act
act
act
act
random
act
497 0.18108651911468815
act
act
act
act
act
act
random
act
act
act
498 0.18072289156626506
act
act
act
random
act
random
act
act
random
act
499 0.18036072144288579
act
act
act
act
act
act
act
act
act
random
500 0.18
act
act
act
act
act
act
act
act
act
act
501 0.17964071856287425
act
act
random
act
act
act
act
act
act
act
502 0.17928286852589642
act
random
act
act
act
act
act
act
act
act
503 0.17892644135188868
act
random
act
random
act
act
random
act
act
random
504 0.17857142857142858
act
act
act
act
act
act
act
act
act
act
505 0.17821782178217824
act
act
act
act
act
act
act
act
random
act
506 0.17786561264822137
act
act
act
act
act
act
act
act
act
act
507 0.1775147928994083
act
act
act
act
act
act
act
act
random
act


act
act
random
act
random
act
act
act
act
act
730 0.1232876712328767
act
act
act
act
act
act
act
act
act
act
731 0.12311901504787962
act
act
act
act
act
act
act
act
act
random
732 0.12295081967213116
act
act
act
act
act
act
act
act
act
act
733 0.12278308321964529
random
act
act
act
random
act
act
act
act
random
734 0.1226158038147139
act
act
act
act
act
act
act
act
act
act
735 0.12244897959183673
random
act
act
act
random
act
act
act
act
act
736 0.12228260869565219
act
act
act
random
act
random
act
act
act
act
737 0.12211668928086838
act
act
act
act
act
act
act
act
act
act
738 0.12195121951219512
act
act
act
random
act
act
act
act
act
act
739 0.12178619756427606
act
act
act
act
random
act
act
act
act
act
740 0.12162162162162161
act
act
act
random
act
act
act
act
act
act
741 0.12145748987854252
act
act
act
act
act
act
random
act
act
act
742 0.12129380053908356
act
act
act
act
act
act
act
act
act
act
743 0.12113055181695827
random
act
act
act
act
act
act
act
act
act
744 0.120967741935483

act
act
random
act
act
act
act
random
act
963 0.09345794392523366
act
random
act
act
random
random
act
random
act
act
964 0.09336099585062241
act
act
act
act
act
random
act
random
act
act
965 0.09326424870466321
act
act
act
act
act
act
random
act
act
act
966 0.09316770186335403
act
act
act
act
act
act
act
act
act
act
967 0.09307135470527404
act
act
act
act
act
act
act
act
act
random
968 0.09297520661157024
act
act
act
act
act
act
act
act
act
act
969 0.09287925696594428
act
act
random
act
act
act
act
act
act
act
970 0.09278350515463918
act
act
act
act
act
act
act
act
act
act
971 0.09268795056642637
act
random
random
act
act
act
act
act
act
act
972 0.0925925925925926
act
act
random
act
act
act
act
act
act
act
973 0.09249743062692703
act
act
random
act
act
act
act
act
act
random
974 0.09240246406570841
act
act
act
act
act
random
act
random
act
act
975 0.0923076923076923
act
act
act
act
act
act
act
act
act
random
976 0.09221311475409837
act
act
act
act
act
act
act
act
act
act
977 0.0921187

In [13]:
breakout_env.reset()
reinforce_agent = AgentReinforce(breakout_env.observation_space, breakout_env.action_space)
steps = 1000
epsilon = 0.9*100
for s in range(1, steps+1):

    done = False
    state = breakout_env.reset()
    total_reward = 0
    rewards = []
    states = []
    actions = []
    for i in range(1500):
        #env.render()
        # alternate
        p = np.random.random()
        if p < 1 - epsilon:
            action = reinforce_agent.act(state)
        else 
            action = np.random.randint(3)
            
#         print("b", action)
        next_state, reward, done = breakout_env.step(action)
        rewards.append(reward)
        states.append(state)
        actions.append(action)
        state = next_state
        total_reward += reward

#         if done:
#             print(state)
#             print(action)
#             print(reward)
    reinforce_agent.train(states, rewards, actions)
    epsilon = (epsilon/s)*100
            #print("total step for this episord are {}".format(t))
    print("total reward after {} steps is {}".format(s, total_reward))

total reward after 0 steps is -289.1999999999944
total reward after 1 steps is -283.5999999999946


KeyboardInterrupt: 

In [ ]:
print("action space: ", breakout_env.action_space)
print("observation space: ", breakout_env.observation_space)

In [14]:
dist = tfp.distributions.Categorical(probs=[0.1, 0.5, 0.4], dtype=tf.float32)
l = dist.sample()
l.numpy()

2.0

In [1]:
from tensorflow import keras

In [2]:
model = keras.models.load_model('policy_gradient_reinforce_model')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
import json
from keras.models import model_from_json

with open('model_architecture.json', 'r') as json_file:
    model = model_from_json(json_file.read())

In [3]:
pip show tensorflow

Name: tensorflow
Version: 2.3.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\programdata\anaconda3\lib\site-packages
Requires: gast, numpy, wheel, opt-einsum, six, google-pasta, protobuf, h5py, tensorboard, tensorflow-estimator, keras-preprocessing, termcolor, wrapt, grpcio, absl-py, scipy, astunparse
Required-by: 
Note: you may need to restart the kernel to use updated packages.
